# Generated by Django 4.1.7 on 2023-03-20 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4)])),
                ('recipe_type', models.CharField(choices=[('Salad', 'Salad'), ('Soup', 'Soup'), ('Appetizer', 'Appetizer'), ('Main Dish', 'Main Dish'), ('Dessert', 'Dessert')], max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
