# Generated by Django 4.1.7 on 2023-03-24 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_userprofile_created_recipes'),
        ('web', '0002_alter_recipes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
