# Generated by Django 4.1.7 on 2023-03-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipe_app.auth_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=20, validators=[recipe_app.auth_app.validators.validate_name])),
                ('last_name', models.CharField(max_length=20, validators=[recipe_app.auth_app.validators.validate_name])),
                ('email', models.EmailField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=255)),
            ],
        ),
    ]
