# Generated by Django 4.1.7 on 2023-03-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userprofile_created_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_recipes',
        ),
    ]
